name    "musicbrainz-server"
maintainer        "retux"
maintainer_email  "matiasgutierrezreto@gmail.com"
license           "Apache 2.0"
description       "musicbrainz server from git. Tested on Ubuntu 14.04."
version "0.0.2"
depends "apt"
depends "build-essential"
depends "daemontools"
depends "nginx"
depends "logster"
depends "runit"
